### ISSUE TITLE
Update check_synology script from 2.5 to 2.6

### ISSUE THREAD

**Issue by cjfranko** [NEMSLinux/nems-plugins#2]
Currently the deployed templates for check_synology don't work as they require the -t argument.

The current release of NEMs (1.6) has the version 2.5 script. 

This new argument was introduced in version 2.6, I have tested by updating the script on my deployment and the snmp calls are successful after updating. 

https://github.com/corben2/check_snmp_synology

**Comment by NEMSLinux** [comment]
Done. Thank you for reporting the issue (as well as the solution). Pushed to the repos, so all 1.6+ servers are updated.
