### ISSUE TITLE
Issue with check_esxi_hardware in 1.6 (RasPi)

### ISSUE THREAD

**Issue by esher72** [NEMSLinux/nems-plugins#3]
It looks like check_esxi_hardware requires python3 but when it is running, it is using python 2. 

     user@nems:/usr/lib/nagios/plugins $ python check_esxi_hardware.py
     Traceback (most recent call last):
       File "check_esxi_hardware.py", line 267, in <module>
         import pywbem
     ImportError: No module named pywbem

     user@nems:/usr/lib/nagios/plugins $ python3 check_esxi_hardware.py
     no parameters specified

      Usage: check_esxi_hardware.py -H hostname -U username -P password [-C port -V system -v -p -I XX]
     ...

     user@nems:/usr/lib/nagios/plugins $ which python
     /usr/bin/python

     user@nems:/usr/lib/nagios/plugins $ /usr/bin/python --version
     Python 2.7.18

I can run it using python3 manually and it works fine.

**Comment by esher72** [comment]
Just an FYI, a quick and dirty fix for me was to change the first line of the check_esxi-hardware.py script to use python3 and it is working now. 

     #!/usr/bin/python3 
     # -*- coding: UTF-8 -*-
     #
     # Script for checking global health of host running VMware ESX/ESXi

**Comment by NEMSLinux** [comment]
`pywbem` has been added to NEMS Linux 1.7. Let me know if you have any more trouble.
